apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-web
  namespace: netflix-dev
  labels:
    app: netflix-web
    environment: dev

spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-web

  template:
    metadata:
      labels:
        app: netflix-web
        environment: dev

    spec:
      containers:
        - name: netflix-web
          image: netflixappdevacr.azurecr.io/netflix-app:v2   # ✅ FIXED (AMD64 working build)
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: netflix-app-config

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-api
  namespace: netflix-dev
  labels:
    app: netflix-api
    environment: dev

spec:
  replicas: 1
  progressDeadlineSeconds: 900

  selector:
    matchLabels:
      app: netflix-api

  template:
    metadata:
      labels:
        app: netflix-api
        environment: dev

    spec:
      automountServiceAccountToken: false

      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: netflix-api
          image: netflixappdevacr.azurecr.io/netflix-api:v3
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          envFrom:
            - secretRef:
                name: netflix-app-secrets

          env:
            - name: HF_HOME
              value: /tmp/huggingface
            - name: TRANSFORMERS_CACHE
              value: /tmp/huggingface

          volumeMounts:
            - name: tmp-storage
              mountPath: /tmp

          resources:
            requests:
              cpu: "200m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"

      volumes:
        - name: tmp-storage
          emptyDir: {}