apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-web
  namespace: netflix-prod
  labels:
    app: netflix-web
    environment: prod

spec:
  replicas: 3
  progressDeadlineSeconds: 900

  selector:
    matchLabels:
      app: netflix-web

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: netflix-web
        environment: prod

    spec:
      automountServiceAccountToken: false

      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: netflix-web
          image: netflixappdevacr.azurecr.io/netflix-app:v2
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: netflix-app-config

          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - ALL

          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10