apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-api-green
  namespace: netflix-prod
  labels:
    app: netflix-api
    slot: green
    environment: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-api
      slot: green
  template:
    metadata:
      labels:
        app: netflix-api
        slot: green
        environment: prod
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsNonRoot: false
      containers:
        - name: netflix-api
          image: netflixappdevacr.azurecr.io/netflix-api:v3
          ports:
            - containerPort: 8080

          env:
            - name: HF_HOME
              value: /tmp/hf
            - name: TRANSFORMERS_CACHE
              value: /tmp/hf

          volumeMounts:
            - name: tmp
              mountPath: /tmp

          envFrom:
            - secretRef:
                name: netflix-app-secrets

      volumes:
        - name: tmp
          emptyDir: {}