apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-web-blue
  namespace: netflix-prod
  labels:
    app: netflix-web
    slot: blue
    environment: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netflix-web
      slot: blue
  template:
    metadata:
      labels:
        app: netflix-web
        slot: blue
        environment: prod
    spec:
      containers:
        - name: netflix-web
          image: netflixappdevacr.azurecr.io/netflix-app:1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: netflix-app-config
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-api-blue
  namespace: netflix-prod
  labels:
    app: netflix-api
    slot: blue
    environment: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-api
      slot: blue
  template:
    metadata:
      labels:
        app: netflix-api
        slot: blue
        environment: prod
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsNonRoot: false   # IMPORTANT FIX (prevents /home/appuser crash)
      containers:
        - name: netflix-api
          image: netflixappdevacr.azurecr.io/netflix-api:v3
          ports:
            - containerPort: 8080

          env:
            - name: HF_HOME
              value: /tmp/hf
            - name: TRANSFORMERS_CACHE
              value: /tmp/hf

          volumeMounts:
            - name: tmp
              mountPath: /tmp

          envFrom:
            - secretRef:
                name: netflix-app-secrets

          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 2Gi

      volumes:
        - name: tmp
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-web-green
  namespace: netflix-prod
  labels:
    app: netflix-web
    slot: green
    environment: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netflix-web
      slot: green
  template:
    metadata:
      labels:
        app: netflix-web
        slot: green
        environment: prod
    spec:
      containers:
        - name: netflix-web
          image: netflixappdevacr.azurecr.io/netflix-app:v1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: netflix-app-config