name: CI - Build and Push Images

on:
  push:
    branches: [main, develop]

env:
  ACR_LOGIN_SERVER: netflixappprodacr.azurecr.io
  ACR_NAME: netflixappprodacr

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: az acr login --name $ACR_NAME

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build API image
        run: |
          docker build -t $ACR_LOGIN_SERVER/netflix-api:$IMAGE_TAG ./api

      - name: Build Web image
        run: |
          docker build -t $ACR_LOGIN_SERVER/netflix-app:$IMAGE_TAG ./web

      - name: Push API image
        run: |
          docker push $ACR_LOGIN_SERVER/netflix-api:$IMAGE_TAG

      - name: Push Web image
        run: |
          docker push $ACR_LOGIN_SERVER/netflix-app:$IMAGE_TAG

      - name: Output image tag
        run: echo "IMAGE_TAG=$IMAGE_TAG"
#