name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Image tag from dev deployment e.g 5fe40ad"
        required: true
        type: string

      confirm_deploy:
        description: "Type deploy-prod to confirm"
        required: true
        type: string


env:

  PROD_ACR_NAME: netflixappprodacruks
  PROD_ACR_LOGIN_SERVER: netflixappprodacruks.azurecr.io

  DEV_ACR_NAME: netflixappdevacr
  DEV_ACR_LOGIN_SERVER: netflixappdevacr.azurecr.io


  AKS_CLUSTER_NAME: netflix-app-prod-aks
  AKS_RESOURCE_GROUP: netflix-app-prod-rg


  NAMESPACE: netflix-prod


  FRONTEND_IMAGE: netflix-web
  API_IMAGE: netflix-api


permissions:

  id-token: write
  contents: read


jobs:


# ==========================================
# Validate Deployment
# ==========================================

  validate:

    runs-on: ubuntu-latest

    steps:

      - name: Validate approval

        run: |

          if [ "${{ github.event.inputs.confirm_deploy }}" != "deploy-prod" ]

          then

            echo "Wrong confirmation"

            exit 1

          fi


          echo "Production deployment approved"



# ==========================================
# Verify images exist in Dev ACR
# ==========================================

  verify-images:

    runs-on: ubuntu-latest

    needs: validate


    steps:


      - name: Azure Login

        uses: azure/login@v2

        with:

          client-id: ${{ secrets.AZURE_CLIENT_ID }}

          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}



      - name: Login Dev ACR

        run: |

          az acr login \
            --name ${{ env.DEV_ACR_NAME }}



      - name: Verify Frontend Image

        run: |

          echo "Checking frontend image"

          az acr repository show-tags \
            --name ${{ env.DEV_ACR_NAME }} \
            --repository ${{ env.FRONTEND_IMAGE }} \
            --output table



      - name: Verify API Image

        run: |

          echo "Checking API image"

          az acr repository show-tags \
            --name ${{ env.DEV_ACR_NAME }} \
            --repository ${{ env.API_IMAGE }} \
            --output table



# ==========================================
# Promote Images Dev ACR -> Prod ACR
# ==========================================

  promote-images:

    runs-on: ubuntu-latest

    needs: verify-images


    steps:


      - name: Azure Login

        uses: azure/login@v2

        with:

          client-id: ${{ secrets.AZURE_CLIENT_ID }}

          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}



      - name: Import Frontend Image

        run: |

          echo "Importing frontend image"


          az acr import \
            --name ${{ env.PROD_ACR_NAME }} \
            --source ${{ env.DEV_ACR_LOGIN_SERVER }}/${{ env.FRONTEND_IMAGE }}:${{ github.event.inputs.image_tag }} \
            --image ${{ env.FRONTEND_IMAGE }}:${{ github.event.inputs.image_tag }} \
            --force



      - name: Import API Image

        run: |

          echo "Importing API image"


          az acr import \
            --name ${{ env.PROD_ACR_NAME }} \
            --source ${{ env.DEV_ACR_LOGIN_SERVER }}/${{ env.API_IMAGE }}:${{ github.event.inputs.image_tag }} \
            --image ${{ env.API_IMAGE }}:${{ github.event.inputs.image_tag }} \
            --force



# ==========================================
# Deploy To AKS
# ==========================================

  deploy-prod:

    runs-on: ubuntu-latest

    needs: promote-images


    steps:


      - name: Checkout

        uses: actions/checkout@v4



      - name: Azure Login

        uses: azure/login@v2

        with:

          client-id: ${{ secrets.AZURE_CLIENT_ID }}

          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}



      - name: Get AKS Credentials

        run: |

          az aks get-credentials \
            --resource-group ${{ env.AKS_RESOURCE_GROUP }} \
            --name ${{ env.AKS_CLUSTER_NAME }} \
            --overwrite-existing



      - name: Create Namespace

        run: |

          kubectl create namespace ${{ env.NAMESPACE }} \
            --dry-run=client -o yaml | kubectl apply -f -



      # ADDED FIX
      - name: Create ConfigMap

        run: |

          kubectl create configmap netflix-app-config \
            --namespace ${{ env.NAMESPACE }} \
            --from-literal=ENVIRONMENT=production \
            --dry-run=client -o yaml | kubectl apply -f -



      - name: Create Secrets

        run: |

          kubectl create secret generic netflix-app-secrets \
            --namespace ${{ env.NAMESPACE }} \
            --from-literal=TMDB_API_KEY=${{ secrets.TMDB_API_KEY }} \
            --dry-run=client -o yaml | kubectl apply -f -



      - name: Deploy Kubernetes Manifests

        run: |

          sed \
            -e "s|__ACR_LOGIN_SERVER__|${{ env.PROD_ACR_LOGIN_SERVER }}|g" \
            -e "s|__IMAGE_TAG__|${{ github.event.inputs.image_tag }}|g" \
            k8s/prod/deployment.yml | kubectl apply -f -


          kubectl apply -f k8s/prod/service.yml -n ${{ env.NAMESPACE }}

          kubectl apply -f k8s/prod/ingress.yml -n ${{ env.NAMESPACE }}

          kubectl apply -f k8s/prod/hpa.yml -n ${{ env.NAMESPACE }}



      - name: Wait For Rollout

        run: |

          kubectl rollout status deployment/netflix-web \
            -n ${{ env.NAMESPACE }} \
            --timeout=600s


          kubectl rollout status deployment/netflix-api \
            -n ${{ env.NAMESPACE }} \
            --timeout=600s



      - name: Verify Production

        run: |

          kubectl get pods -n ${{ env.NAMESPACE }}

          kubectl get svc -n ${{ env.NAMESPACE }}

          kubectl get ingress -n ${{ env.NAMESPACE }}
#