name: DEV CI/CD

on:
  push:
    branches:
      - develop

env:
  ACR_LOGIN_SERVER: netflixappdevacr.azurecr.io
  ACR_NAME: netflixappdevacr
  AKS_CLUSTER_NAME: netflix-app-dev-aks
  AKS_RESOURCE_GROUP: netflix-app-dev-rg-we
  NAMESPACE: netflix-dev

permissions:
  id-token: write
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set image tag
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Login to ACR
        run: az acr login --name $ACR_NAME

      - name: Build & Push Images
        run: |
          echo "Building images with tag: $IMAGE_TAG"

          docker build -t $ACR_LOGIN_SERVER/netflix-app:$IMAGE_TAG .
          docker build -t $ACR_LOGIN_SERVER/netflix-api:$IMAGE_TAG .

          docker push $ACR_LOGIN_SERVER/netflix-app:$IMAGE_TAG
          docker push $ACR_LOGIN_SERVER/netflix-api:$IMAGE_TAG

      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group $AKS_RESOURCE_GROUP \
            --name $AKS_CLUSTER_NAME \
            --overwrite-existing

      - name: Deploy to DEV
        run: |
          echo "Deploying to DEV with tag: $IMAGE_TAG"

          sed -e "s|__ACR_LOGIN_SERVER__|$ACR_LOGIN_SERVER|g" \
              -e "s|__IMAGE_TAG__|$IMAGE_TAG|g" \
              k8s/dev/deployment.yml | kubectl apply -n $NAMESPACE -f -

          kubectl apply -n $NAMESPACE -f k8s/dev/service.yml
          kubectl apply -n $NAMESPACE -f k8s/dev/ingress.yml

      - name: Verify rollout
        run: |
          kubectl rollout status deployment/netflix-web -n $NAMESPACE --timeout=300s
          kubectl rollout status deployment/netflix-api -n $NAMESPACE --timeout=300s

      - name: Show pods
        run: |
          kubectl get pods -n $NAMESPACE
          kubectl get svc -n $NAMESPACE