name: Deploy Monitoring Stack

on:
  workflow_dispatch:
    inputs:

      environment:
        description: "Target environment"
        required: true
        type: choice
        options:
          - dev
          - production


env:

  AKS_CLUSTER_NAME_DEV: netflix-app-dev-aks
  AKS_RESOURCE_GROUP_DEV: netflix-app-dev-rg

  AKS_CLUSTER_NAME_PROD: netflix-app-prod-aks
  AKS_RESOURCE_GROUP_PROD: netflix-app-prod-rg-uks


  MONITORING_NAMESPACE: monitoring


permissions:

  id-token: write
  contents: read



jobs:


# ==========================================
# Deploy Monitoring Stack
# ==========================================

  deploy-monitoring:


    name: Deploy kube-prometheus-stack


    runs-on: ubuntu-latest


    environment: ${{ inputs.environment }}


    steps:



# ------------------------------------------
# Checkout
# ------------------------------------------

      - name: Checkout code

        uses: actions/checkout@v4




# ------------------------------------------
# Azure Login
# ------------------------------------------

      - name: Azure Login OIDC

        uses: azure/login@v2

        with:

          client-id: ${{ secrets.AZURE_CLIENT_ID }}

          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}





# ------------------------------------------
# Select AKS Cluster
# ------------------------------------------

      - name: Set cluster variables

        id: cluster

        shell: bash

        run: |


          if [ "${{ inputs.environment }}" = "production" ]

          then


            echo "cluster_name=${{ env.AKS_CLUSTER_NAME_PROD }}" >> $GITHUB_OUTPUT

            echo "resource_group=${{ env.AKS_RESOURCE_GROUP_PROD }}" >> $GITHUB_OUTPUT


          else


            echo "cluster_name=${{ env.AKS_CLUSTER_NAME_DEV }}" >> $GITHUB_OUTPUT

            echo "resource_group=${{ env.AKS_RESOURCE_GROUP_DEV }}" >> $GITHUB_OUTPUT


          fi





# ------------------------------------------
# Debug
# ------------------------------------------

      - name: Show selected cluster

        run: |


          echo "AKS Cluster:"
          echo "${{ steps.cluster.outputs.cluster_name }}"


          echo "Resource Group:"
          echo "${{ steps.cluster.outputs.resource_group }}"





# ------------------------------------------
# AKS Credentials
# ------------------------------------------

      - name: Get AKS Credentials

        run: |


          az aks get-credentials \
            --resource-group "${{ steps.cluster.outputs.resource_group }}" \
            --name "${{ steps.cluster.outputs.cluster_name }}" \
            --overwrite-existing





# ------------------------------------------
# Install Helm
# ------------------------------------------

      - name: Install Helm

        uses: azure/setup-helm@v4






# ------------------------------------------
# Create Namespace
# ------------------------------------------

      - name: Create Monitoring Namespace

        run: |


          kubectl create namespace ${{ env.MONITORING_NAMESPACE }} \
          --dry-run=client \
          -o yaml | kubectl apply -f -





# ------------------------------------------
# Add Helm Repo
# ------------------------------------------

      - name: Add Prometheus Helm Repo

        run: |


          helm repo add prometheus-community \
          https://prometheus-community.github.io/helm-charts


          helm repo update





# ------------------------------------------
# Deploy Prometheus + Grafana
# ------------------------------------------

      - name: Deploy kube-prometheus-stack

        run: |


          helm upgrade --install kube-prometheus-stack \
          prometheus-community/kube-prometheus-stack \
          --namespace ${{ env.MONITORING_NAMESPACE }} \
          --create-namespace \
          --values k8s/monitoring/helm-values.yml \
          --set grafana.adminPassword=${{ secrets.GRAFANA_ADMIN_PASSWORD }} \
          --atomic \
          --wait \
          --timeout 15m





# ------------------------------------------
# Deploy Dashboard ConfigMap
# ------------------------------------------

      - name: Deploy Netflix Dashboard

        run: |


          kubectl apply \
          -f k8s/monitoring/netflix-dashboard-cm.yml \
          -n ${{ env.MONITORING_NAMESPACE }}







# ------------------------------------------
# Verify Pods
# ------------------------------------------

      - name: Check Monitoring Pods

        run: |


          kubectl get pods \
          -n ${{ env.MONITORING_NAMESPACE }}






# ------------------------------------------
# Display Services
# ------------------------------------------

      - name: Display Monitoring Services

        run: |


          echo "===== SERVICES ====="


          kubectl get svc \
          -n ${{ env.MONITORING_NAMESPACE }}





# ------------------------------------------
# Get Grafana URL
# ------------------------------------------

      - name: Display Grafana Endpoint

        run: |


          GRAFANA_IP=$(kubectl get svc kube-prometheus-stack-grafana \
          -n ${{ env.MONITORING_NAMESPACE }} \
          -o jsonpath='{.status.loadBalancer.ingress[0].ip}')


          echo ""

          echo "================================"

          echo "Grafana URL: http://${GRAFANA_IP}"

          echo "Username: admin"

          echo "Password: your GitHub secret GRAFANA_ADMIN_PASSWORD"

          echo "================================"